
@email = john.doe@email.com
@fullName = John Doe
@password = Pwd@123

# @name create_user
POST {{apiUrl}}/users
Content-Type: application/json

{
  "email": "{{email}}",
  "fullName": "{{fullName}}",
  "password": "{{password}}"
}
###

# @name authenticate_user
POST {{apiUrl}}/users/authenticate
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
###

# @name find_many_users
GET {{apiUrl}}/users
Authorization: Bearer {{authenticate_user.response.body.accessToken}}
###

# @name delete_user
DELETE {{apiUrl}}/users/{{find_many_users.response.body.0.id}}
Authorization: Bearer {{authenticate_user.response.body.accessToken}}
###