@email = jessie.doe@email.com
@password = Pwd@123

# @name authenticate_user
POST {{apiUrl}}/users/authenticate
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
###

@accessToken = Bearer {{authenticate_user.response.body.accessToken}}

# @name create_charge
POST {{apiUrl}}/charges
Content-Type: application/json
Authorization: {{accessToken}}

{
  "paymentMethod": "BOLETO",
  "amount": 100,
  "description": "Teste de cobrança",
  "receivedById": "260e26c9-6154-483e-838b-dd2e09d4286c"
}
###

# @name find_charges_from_current_user
GET {{apiUrl}}/charges
Content-Type: application/json
Authorization: {{accessToken}}

###

# @name get_pix_data
GET {{apiUrl}}/charges/pay_uoigza69ble13mm6/pix-data
Content-Type: application/json
Authorization: {{accessToken}}

###
